<?php


# Array associativo com a lista de estados
$nomesEstados = [
    "AC" => "Acre", 
    "AL" => "Alagoas", 
    "AP" => "Amapá", 
    "AM" => "Amazonas", 
    "BA" => "Bahia", 
    "CE" => "Ceará", 
    "DF" => "Distrito Federal", 
    "ES" => "Espiríto Santo", 
    "GO" => "Gôiania", 
    "MA" => "Maranhão", 
    "MT" => "Mato Grosso", 
    "MS" => "Mato Grosso do Sul", 
    "MG" => "Minas Gerais", 
    "PA" => "Pará", 
    "PB" => "Paraibá", 
    "PR" => "Paraná", 
    "PE" => "Pernanbuco", 
    "PI" => "Piauí", 
    "RJ" => "Rio de Janeiro", 
    "RN" => "Rio Grande Do Norte", 
    "RS" => "Rio Grande Do Sul", 
    "RO" => "Rondônia", 
    "RR" => "Roraima", 
    "SC" => "Santa Catarina", 
    "SP" => "São Paulo", 
    "SE" => "Sergipe", 
    "TO" => "Tocantins", 
];


$correcao = [
    "AC" => "Do", 
    "AL" => "De", 
    "AP" => "Do", 
    "AM" => "Do", 
    "BA" => "Da", 
    "CE" => "Do", 
    "DF" => "Do", 
    "ES" => "Do", 
    "GO" => "De", 
    "MA" => "Do", 
    "MT" => "Do", 
    "MS" => "Do", 
    "MG" => "De", 
    "PA" => "Do", 
    "PB" => "Da", 
    "PE" => "De", 
    "PB" => "De", 
    "PI" => "Do", 
    "RJ" => "Do", 
    "RN" => "Do", 
    "RS" => "Do", 
    "RO" => "De", 
    "RR" => "De", 
    "SC" => "De", 
    "SP" => "De", 
    "SE" => "De", 
    "TO" => "De", 

];